### PR TITLE
Allow auth with X-API-KEY header instead of Authorization header

### PR DESCRIPTION
**Pull request by derekantrican**
Resolves discussion #60

_I also have pending changes to turn this on & off via a setting. Let me know if you would like me to commit those._

_Part of me also wants to add a setting to make this user-customizable (eg something other than `X-API-KEY`) but maybe this is fine. Again, let me know your thoughts._

### CODE REVIEW

**Comment by derekantrican** [comment]
I will imagine I will have to update some documentation somewhere - just point me in the right direction

**Comment by derekantrican** [comment]
@coddingtonbear any opinions on this? Could this be merged?

**Comment by coddingtonbear** [comment]
OK, I made similar changes to what you were using via https://github.com/coddingtonbear/obsidian-local-rest-api/pull/65 -- the main difference is that I went the approach of just making the name of the header containing the authorization information configurable.

This'll go out as part of the next release, which I hope to find some time to do within the next few days.

**Comment by derekantrican** [comment]
Awesome! That was a lot faster than I expected!

I'll check it out when I next get a chance (either tomorrow or Monday) but sounds great

**Pull request merged**
